version: '3'
services:
  cassandra:
    build: './docker/cassandra'
    container_name: cassandra
    ports:
      - '9042:9042'
  spark-master:
    build: './docker/spark/spark-master'
    container_name: spark-master
    hostname: "spark-master"
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - ENABLE_INIT_DAEMON=false
    depends_on:
      - cassandra
    volumes:
      - './mnt/spark/spark-apps:/opt/spark-apps'
      - './mnt/spark/spark-data:/opt/spark-data'
